### ISSUE TITLE
Remaining dependencies on retired package rgdal

### ISSUE THREAD

**Issue by TobiasMy** [ifellows/ROSM#18]
I just stumbled across this package today and it looks quite interesting. Unfortunately function openmap() does not work as it still seems to use an spTransform() which requires rgdal (which has been retired October 2023).

Maybe there's an easy fix to make this work with current packages?

```R
projectMercator <- function(lat,long,drop=TRUE){
	df <- data.frame(long=long,lat=lat)
	coordinates(df) <- ~long+lat
	proj4string(df) <- CRS("+proj=longlat +datum=WGS84")
	df1 <- spTransform(df,osm())
	coords <- coordinates(df1)
	colnames(coords) <- c("x","y")
	if(drop)
		coords <- drop(coords)
	coords
}
```

**Comment by ifellows** [comment]
This function is calling `spTransform` from the `sp` package, which is not retired.

**Comment by TobiasMy** [comment]
Indeed. Thanks for the quick reply. I figured out that the issue was an outdated version of the `sp` package on my part which caused the error saying `rgdal` was required.
